# Generated by Django 5.0.6 on 2025-08-02 13:45

from django.db import migrations
import os

def load_provinces(apps, schema_editor):
    sql_path = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'data', 'provinces.sql')
    with open(sql_path, encoding='utf-8') as f:
        sql = f.read()
    schema_editor.execute(sql)

def reverse_provinces(apps, schema_editor):
    schema_editor.execute("DELETE FROM core_province;")

class Migration(migrations.Migration):
    dependencies = [
        ('core', '0001_initial'),
    ]
    operations = [
        migrations.RunPython(load_provinces, reverse_provinces),
    ]
