# Generated by Django 5.0.6 on 2025-08-02 13:45

from django.db import migrations
import os

def load_cities(apps, schema_editor):
    sql_path = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'data', 'cities.sql')
    with open(sql_path, encoding='utf-8') as f:
        sql = f.read()
    schema_editor.execute(sql)

def reverse_cities(apps, schema_editor):
    schema_editor.execute("DELETE FROM core_city;")

class Migration(migrations.Migration):
    dependencies = [
        ('core', '0002_add_provinces_data'),
    ]
    operations = [
        migrations.RunPython(load_cities, reverse_cities),
    ]
