# Generated by Django 5.0.6 on 2025-08-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='instagram_link',
            field=models.URLField(blank=True, verbose_name='لینک اینستاگرام'),
        ),
        migrations.AddField(
            model_name='post',
            name='telegram_link',
            field=models.URLField(blank=True, verbose_name='لینک تلگرام'),
        ),
    ]
