# Generated by Django 5.0.6 on 2025-08-10 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_instagram_link_post_telegram_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='ایمیل')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ اشتراک')),
            ],
            options={
                'verbose_name': 'اشتراک خبرنامه',
                'verbose_name_plural': 'اشتراک\u200cهای خبرنامه',
                'ordering': ['-subscribed_at'],
            },
        ),
    ]
