# Generated by Django 5.0.6 on 2025-08-05 06:18

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته\u200cبندی')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='اسلاگ')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='آیکون')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام محصول')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='توضیحات کوتاه')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت')),
                ('original_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='قیمت اصلی')),
                ('discount_percentage', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درصد تخفیف')),
                ('discount_amount', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='مبلغ تخفیف')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='موجودی')),
                ('min_stock_alert', models.PositiveIntegerField(default=5, verbose_name='حداقل موجودی هشدار')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='برند')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='مدل')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='رنگ')),
                ('size', models.CharField(blank=True, max_length=50, verbose_name='سایز')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='وزن (گرم)')),
                ('dimensions', models.CharField(blank=True, max_length=100, verbose_name='ابعاد')),
                ('is_featured', models.BooleanField(default=False, verbose_name='محصول ویژه')),
                ('is_bestseller', models.BooleanField(default=False, verbose_name='پرفروش')),
                ('is_new', models.BooleanField(default=False, verbose_name='جدید')),
                ('is_luxury', models.BooleanField(default=False, verbose_name='لوکس')),
                ('has_discount', models.BooleanField(default=False, verbose_name='دارای تخفیف')),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز')),
                ('review_count', models.PositiveIntegerField(default=0, verbose_name='تعداد نظرات')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('inactive', 'غیرفعال'), ('out_of_stock', 'ناموجود')], default='active', max_length=20, verbose_name='وضعیت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='عنوان متا')),
                ('meta_description', models.TextField(blank=True, verbose_name='توضیحات متا')),
                ('meta_keywords', models.CharField(blank=True, max_length=500, verbose_name='کلمات کلیدی متا')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='تصویر')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='متن جایگزین')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='عنوان')),
                ('is_primary', models.BooleanField(default=False, verbose_name='تصویر اصلی')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'تصویر محصول',
                'verbose_name_plural': 'تصاویر محصولات',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام مشخصه')),
                ('value', models.CharField(max_length=500, verbose_name='مقدار')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='shop.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'مشخصه محصول',
                'verbose_name_plural': 'مشخصات محصولات',
                'ordering': ['order'],
            },
        ),
    ]
