# Generated by Django 5.0.6 on 2025-08-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='facebook_link',
            field=models.URLField(blank=True, verbose_name='لینک فیسبوک'),
        ),
        migrations.AddField(
            model_name='product',
            name='instagram_link',
            field=models.URLField(blank=True, verbose_name='لینک اینستاگرام'),
        ),
        migrations.AddField(
            model_name='product',
            name='telegram_link',
            field=models.URLField(blank=True, verbose_name='لینک تلگرام'),
        ),
    ]
