# Generated by Django 5.0.6 on 2025-08-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان بنر')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='زیرعنوان')),
                ('button_text', models.CharField(default='همین حالا خرید کنید', max_length=50, verbose_name='متن دکمه')),
                ('button_url', models.CharField(default='#', max_length=200, verbose_name='لینک دکمه')),
                ('discount_percentage', models.IntegerField(default=30, verbose_name='درصد تخفیف')),
                ('countdown_hours', models.IntegerField(default=48, verbose_name='ساعت باقی\u200cمانده')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('banner_type', models.CharField(choices=[('hero', 'بنر اصلی'), ('promo', 'بنر تبلیغاتی'), ('category', 'بنر دسته\u200cبندی')], default='hero', max_length=20, verbose_name='نوع بنر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'بنر',
                'verbose_name_plural': 'بنرها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShippingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_cost', models.DecimalField(decimal_places=0, default=70000, max_digits=10)),
                ('free_shipping_threshold', models.DecimalField(decimal_places=0, default=500000, max_digits=10)),
            ],
            options={
                'verbose_name': 'تنظیمات ارسال',
                'verbose_name_plural': 'تنظیمات ارسال',
            },
        ),
    ]
