# Generated by Django 5.0.6 on 2025-08-20 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_authority',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شناسه مرجع پرداخت'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_description',
            field=models.TextField(blank=True, verbose_name='توضیحات پرداخت'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_ref_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره تراکنش'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='کد وضعیت پرداخت'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('processing', 'در حال پردازش'), ('shipped', 'ارسال شد'), ('delivered', 'تحویل شد'), ('canceled', 'لغو شده'), ('payment_failed', 'پرداخت ناموفق')], default='pending', max_length=20, verbose_name='وضعیت'),
        ),
    ]
